# backend/explain/stage4/ollama_adapter.py
"""
Ollama Adapter for Stage 4
==========================

Formats explanation text from Stage 3 into natural Vietnamese using Ollama.

This is a FORMATTER layer, not a reasoning layer:
  - Does NOT add new information
  - Does NOT change meaning
  - Does NOT infer anything
  - Has mandatory fallback

Pipeline position:
    Inference → XAI (GĐ2) → Rule+Template (GĐ3) → Ollama (GĐ4) → API → Frontend
"""

from __future__ import annotations

import hashlib
import json
import logging
import re
import threading
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Set

import yaml

from backend.explain.stage4.client import (
    OllamaClient,
    OllamaResponse,
    get_ollama_client,
)

logger = logging.getLogger("explain.stage4.adapter")

# Stage 4 version
STAGE4_VERSION = "1.0.0"


# ==============================================================================
# Configuration
# ==============================================================================

@dataclass
class Stage4Config:
    """Configuration for Stage 4."""
    
    enabled: bool = True
    model: str = "llama3.2:1b"
    timeout: float = 5.0
    retry: int = 2
    strict_validate: bool = True
    max_output_length: int = 2000
    log_level: str = "full"  # "full" | "minimal" | "off"
    log_dir: str = "logs"
    
    # Validation settings
    hallucination_keywords: List[str] = field(default_factory=lambda: [
        "tôi nghĩ", "có thể", "nên", "khuyên", "gợi ý",
        "thêm vào đó", "ngoài ra còn", "bạn cũng có thể",
        "theo tôi", "tôi đề xuất", "tôi khuyên",
    ])
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Stage4Config":
        """Load from config dict."""
        stage4 = data.get("stage4", data)
        return cls(
            enabled=stage4.get("enabled", True),
            model=stage4.get("model", "llama3.2:1b"),
            timeout=stage4.get("timeout", 5.0),
            retry=stage4.get("retry", 2),
            strict_validate=stage4.get("strict_validate", True),
            max_output_length=stage4.get("max_output_length", 2000),
            log_level=stage4.get("log_level", "full"),
            log_dir=stage4.get("log_dir", "logs"),
        )


# ==============================================================================
# Output Validator
# ==============================================================================

@dataclass
class ValidationResult:
    """Result of output validation."""
    
    valid: bool
    issues: List[str] = field(default_factory=list)
    
    def __bool__(self) -> bool:
        return self.valid


class OutputValidator:
    """
    Validates LLM output to prevent hallucination and ensure quality.
    
    Checks:
      - Not empty
      - No new reasons added
      - No hallucination keywords
      - Not exceeding max length
    """
    
    def __init__(self, config: Stage4Config):
        self._config = config
    
    def validate(
        self,
        llm_output: str,
        original_text: str,
        original_reasons: List[str],
    ) -> ValidationResult:
        """
        Validate LLM output.
        
        Args:
            llm_output: Text generated by LLM
            original_text: Original text from Stage 3
            original_reasons: Original reasons from Stage 3
            
        Returns:
            ValidationResult with valid flag and issues list
        """
        issues = []
        
        # Check 1: Not empty
        if not llm_output or len(llm_output.strip()) == 0:
            issues.append("Output is empty")
            return ValidationResult(valid=False, issues=issues)
        
        # Check 2: Not exceeding max length
        if len(llm_output) > self._config.max_output_length:
            issues.append(
                f"Output too long: {len(llm_output)} > {self._config.max_output_length}"
            )
            if self._config.strict_validate:
                return ValidationResult(valid=False, issues=issues)
        
        # Check 3: Hallucination keywords
        llm_lower = llm_output.lower()
        for keyword in self._config.hallucination_keywords:
            if keyword.lower() in llm_lower:
                issues.append(f"Hallucination keyword detected: '{keyword}'")
                if self._config.strict_validate:
                    return ValidationResult(valid=False, issues=issues)
        
        # Check 4: No new significant content added (diff check)
        # This is a heuristic - check if LLM added many new words
        original_words = set(self._extract_keywords(original_text))
        llm_words = set(self._extract_keywords(llm_output))
        new_words = llm_words - original_words
        
        # Allow some variation (synonyms, rephrasing)
        if len(new_words) > len(original_words) * 0.3:
            issues.append(
                f"Too many new words added: {len(new_words)} new words"
            )
            if self._config.strict_validate:
                return ValidationResult(valid=False, issues=issues)
        
        # Valid if no critical issues
        return ValidationResult(valid=len(issues) == 0 or not self._config.strict_validate, issues=issues)
    
    def _extract_keywords(self, text: str) -> List[str]:
        """Extract significant keywords from text."""
        # Remove common Vietnamese stopwords and punctuation
        stopwords = {
            "và", "là", "của", "có", "được", "cho", "với", "trong",
            "này", "đó", "để", "như", "theo", "về", "các", "những",
            "bạn", "mô", "hình", "vì", "vì:", "...", "độ", "tin",
        }
        
        # Tokenize and filter
        words = re.findall(r'\b\w+\b', text.lower())
        return [w for w in words if w not in stopwords and len(w) > 2]


# ==============================================================================
# Stage 4 Output
# ==============================================================================

@dataclass
class Stage4Output:
    """Output from Stage 4."""
    
    # From Stage 3
    trace_id: str
    career: str
    reasons: List[str]
    confidence: float
    raw_text: str  # Original from Stage 3
    
    # Stage 4 additions
    llm_text: str  # After Ollama formatting
    used_llm: bool
    fallback: bool = False
    
    # Metadata
    stage4_version: str = STAGE4_VERSION
    ollama_model: str = ""
    latency_ms: float = 0.0
    validation_issues: List[str] = field(default_factory=list)
    timestamp: str = ""
    
    def __post_init__(self):
        if not self.timestamp:
            self.timestamp = datetime.now(timezone.utc).isoformat()
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dict for API."""
        return {
            "trace_id": self.trace_id,
            "career": self.career,
            "reasons": self.reasons,
            "confidence": self.confidence,
            "raw_text": self.raw_text,
            "llm_text": self.llm_text,
            "used_llm": self.used_llm,
            "fallback": self.fallback,
            "meta": {
                "stage4_version": self.stage4_version,
                "ollama_model": self.ollama_model,
                "latency_ms": round(self.latency_ms, 2),
            },
            "timestamp": self.timestamp,
        }
    
    def to_api_response(self) -> Dict[str, Any]:
        """Convert to clean API response."""
        return {
            "trace_id": self.trace_id,
            "career": self.career,
            "reasons": self.reasons,
            "confidence": self.confidence,
            "raw_text": self.raw_text,
            "llm_text": self.llm_text,
            "used_llm": self.used_llm,
        }


# ==============================================================================
# Stage 4 Engine
# ==============================================================================

class Stage4Engine:
    """
    Stage 4 Engine - Ollama formatting.
    
    Transforms Stage 3 explanation into natural Vietnamese.
    Has mandatory fallback to Stage 3 output on any failure.
    
    Usage::
    
        engine = Stage4Engine()
        engine.load_config(config)
        
        result = engine.format(stage3_output)
    """
    
    def __init__(self, project_root: Optional[Path] = None):
        self._project_root = project_root or Path(__file__).resolve().parents[3]
        
        # Configuration
        self._config = Stage4Config()
        
        # Ollama client
        self._client = get_ollama_client()
        
        # Validator
        self._validator = OutputValidator(self._config)
        
        # Prompt template
        self._prompt_template = self._load_prompt_template()
        
        # Logging
        self._log_dir = self._project_root / "logs"
        self._log_file: Optional[Path] = None
        self._setup_logging()
        
        self._lock = threading.RLock()
    
    def _load_prompt_template(self) -> str:
        """Load prompt template from file."""
        template_path = Path(__file__).parent / "prompts" / "formatter.txt"
        if template_path.exists():
            return template_path.read_text(encoding="utf-8")
        
        # Fallback template
        return """SYSTEM:
You are a formatter. Do not add new information.
Do not change meaning.
Do not infer anything.

USER:
Rewrite the following explanation in clear Vietnamese.
Keep all facts unchanged.

TEXT:
{{ explain_text }}"""
    
    def _setup_logging(self) -> None:
        """Setup Stage 4 specific logging."""
        self._log_dir.mkdir(parents=True, exist_ok=True)
        self._log_file = self._log_dir / "explain_stage4.log"
    
    def load_config(self, config: Dict[str, Any]) -> None:
        """Load configuration."""
        self._config = Stage4Config.from_dict(config)
        
        # Update validator
        self._validator = OutputValidator(self._config)
        
        # Update client
        self._client.configure(
            model=self._config.model,
            timeout=self._config.timeout,
            max_retries=self._config.retry,
        )
        
        # Update log directory
        if self._config.log_dir:
            self._log_dir = self._project_root / self._config.log_dir
            self._setup_logging()
        
        logger.info(
            f"Stage4 config: enabled={self._config.enabled}, "
            f"model={self._config.model}, timeout={self._config.timeout}s"
        )
    
    def load_config_file(self, config_path: Optional[str] = None) -> None:
        """Load configuration from YAML file."""
        if config_path is None:
            config_path = str(self._project_root / "config" / "explain.yaml")
        
        path = Path(config_path)
        if not path.exists():
            logger.warning(f"Config file not found: {config_path}")
            return
        
        try:
            with open(path, "r", encoding="utf-8") as f:
                config = yaml.safe_load(f) or {}
            self.load_config(config)
        except Exception as e:
            logger.error(f"Failed to load config: {e}")
    
    def format(self, stage3_output: Dict[str, Any]) -> Stage4Output:
        """
        Format Stage 3 output using Ollama.
        
        Args:
            stage3_output: Output from Stage 3
            
        Returns:
            Stage4Output with formatted text or fallback
        """
        with self._lock:
            start_time = time.time()
            
            # Extract Stage 3 data
            trace_id = stage3_output.get("trace_id", "")
            career = stage3_output.get("career", "")
            reasons = stage3_output.get("reasons", [])
            confidence = float(stage3_output.get("confidence", 0.0))
            raw_text = stage3_output.get("explain_text", "")
            
            # Check if enabled
            if not self._config.enabled:
                return self._create_fallback(
                    trace_id, career, reasons, confidence, raw_text,
                    reason="Stage4 disabled"
                )
            
            # Check if raw_text is empty
            if not raw_text or len(raw_text.strip()) == 0:
                return self._create_fallback(
                    trace_id, career, reasons, confidence, raw_text,
                    reason="Empty input text"
                )
            
            # Build prompt
            prompt = self._build_prompt(raw_text)
            system_prompt = self._extract_system_prompt()
            
            # Call Ollama
            try:
                response = self._client.generate(
                    prompt=prompt,
                    system_prompt=system_prompt,
                    temperature=0.3,
                    max_tokens=500,
                )
                
                latency_ms = (time.time() - start_time) * 1000
                
                if not response.success:
                    logger.warning(f"Ollama failed: {response.error}")
                    result = self._create_fallback(
                        trace_id, career, reasons, confidence, raw_text,
                        reason=f"Ollama error: {response.error}",
                        latency_ms=latency_ms,
                    )
                    self._audit_log(result, prompt, response.text)
                    return result
                
                # Validate output
                validation = self._validator.validate(
                    response.text, raw_text, reasons
                )
                
                if not validation.valid:
                    logger.warning(f"Validation failed: {validation.issues}")
                    result = self._create_fallback(
                        trace_id, career, reasons, confidence, raw_text,
                        reason=f"Validation failed: {validation.issues}",
                        latency_ms=latency_ms,
                        validation_issues=validation.issues,
                    )
                    self._audit_log(result, prompt, response.text)
                    return result
                
                # Success
                result = Stage4Output(
                    trace_id=trace_id,
                    career=career,
                    reasons=reasons,
                    confidence=confidence,
                    raw_text=raw_text,
                    llm_text=response.text,
                    used_llm=True,
                    fallback=False,
                    ollama_model=self._config.model,
                    latency_ms=latency_ms,
                    validation_issues=validation.issues,
                )
                
                self._audit_log(result, prompt, response.text)
                return result
                
            except Exception as e:
                latency_ms = (time.time() - start_time) * 1000
                logger.error(f"Stage4 error: {e}")
                result = self._create_fallback(
                    trace_id, career, reasons, confidence, raw_text,
                    reason=f"Exception: {str(e)[:100]}",
                    latency_ms=latency_ms,
                )
                self._audit_log(result, prompt, "")
                return result
    
    def _build_prompt(self, explain_text: str) -> str:
        """Build prompt from template."""
        # Extract USER section from template
        lines = self._prompt_template.split("\n")
        user_section = []
        in_user = False
        
        for line in lines:
            if line.strip().startswith("USER:"):
                in_user = True
                continue
            if in_user:
                user_section.append(line)
        
        user_prompt = "\n".join(user_section)
        
        # Replace placeholder
        return user_prompt.replace("{{ explain_text }}", explain_text)
    
    def _extract_system_prompt(self) -> str:
        """Extract system prompt from template."""
        lines = self._prompt_template.split("\n")
        system_section = []
        in_system = False
        
        for line in lines:
            if line.strip().startswith("SYSTEM:"):
                in_system = True
                continue
            if line.strip().startswith("USER:"):
                break
            if in_system:
                system_section.append(line)
        
        return "\n".join(system_section).strip()
    
    def _create_fallback(
        self,
        trace_id: str,
        career: str,
        reasons: List[str],
        confidence: float,
        raw_text: str,
        reason: str = "",
        latency_ms: float = 0.0,
        validation_issues: Optional[List[str]] = None,
    ) -> Stage4Output:
        """Create fallback output (use Stage 3 text as-is)."""
        logger.info(f"Stage4 fallback: {reason}")
        
        return Stage4Output(
            trace_id=trace_id,
            career=career,
            reasons=reasons,
            confidence=confidence,
            raw_text=raw_text,
            llm_text=raw_text,  # Fallback to raw_text
            used_llm=False,
            fallback=True,
            ollama_model=self._config.model,
            latency_ms=latency_ms,
            validation_issues=validation_issues or [reason],
        )
    
    def _audit_log(
        self,
        result: Stage4Output,
        prompt: str,
        raw_output: str,
    ) -> None:
        """Write audit log entry."""
        if self._config.log_level == "off":
            return
        
        try:
            log_entry = {
                "timestamp": result.timestamp,
                "trace_id": result.trace_id,
                "model": result.ollama_model,
                "latency_ms": round(result.latency_ms, 2),
                "prompt_hash": hashlib.sha256(prompt.encode()).hexdigest()[:16],
                "fallback": result.fallback,
                "used_llm": result.used_llm,
            }
            
            if self._config.log_level == "full":
                log_entry["raw_output"] = raw_output[:500] if raw_output else ""
                log_entry["final_output"] = result.llm_text[:500]
                log_entry["validation_issues"] = result.validation_issues
            
            # Write to log file
            if self._log_file:
                with open(self._log_file, "a", encoding="utf-8") as f:
                    f.write(json.dumps(log_entry, ensure_ascii=False) + "\n")
            
            logger.debug(f"Stage4 audit: {result.trace_id}")
            
        except Exception as e:
            logger.error(f"Failed to write audit log: {e}")
    
    def is_enabled(self) -> bool:
        """Check if Stage 4 is enabled."""
        return self._config.enabled
    
    def health_check(self) -> bool:
        """Check if Ollama is available."""
        return self._client.health_check()


# ==============================================================================
# Singleton & Helper Functions
# ==============================================================================

_stage4_engine: Optional[Stage4Engine] = None


def get_stage4_engine() -> Stage4Engine:
    """Get or create singleton Stage4Engine."""
    global _stage4_engine
    if _stage4_engine is None:
        _stage4_engine = Stage4Engine()
        _stage4_engine.load_config_file()
    return _stage4_engine


def format_with_llm(stage3_output: Dict[str, Any]) -> Dict[str, Any]:
    """
    Format Stage 3 output using Ollama (main entry point).
    
    Args:
        stage3_output: Output from Stage 3
        
    Returns:
        Stage 4 output dict
        
    Example:
        >>> stage3_out = {
        ...     "trace_id": "abc123",
        ...     "career": "Data Scientist",
        ...     "reasons": ["Điểm Toán vượt ngưỡng (shap)"],
        ...     "explain_text": "Bạn phù hợp với Data Scientist vì:...",
        ...     "confidence": 0.87
        ... }
        >>> result = format_with_llm(stage3_out)
        >>> print(result["llm_text"])
    """
    engine = get_stage4_engine()
    result = engine.format(stage3_output)
    return result.to_dict()


# ──────────────────────────────────────────────────────────────────────────────
# Analytical Summary Generator
# ──────────────────────────────────────────────────────────────────────────────

_ANALYTICAL_PROMPT_PATH = Path(__file__).parent / "prompts" / "analytical_explanation.txt"

_analytical_template: Optional[str] = None


def _load_analytical_template() -> str:
    """Load (and cache) the analytical_explanation.txt prompt template."""
    global _analytical_template
    if _analytical_template is None:
        if _ANALYTICAL_PROMPT_PATH.exists():
            _analytical_template = _ANALYTICAL_PROMPT_PATH.read_text(encoding="utf-8")
        else:
            logger.warning("analytical_explanation.txt not found at %s", _ANALYTICAL_PROMPT_PATH)
            _analytical_template = ""
    return _analytical_template


def _split_system_user(template: str) -> tuple[str, str]:
    """Extract (system_prompt, user_prompt) from a SYSTEM:/USER: template."""
    system_prompt = ""
    user_prompt = template
    if "SYSTEM:" in template and "USER:" in template:
        parts = template.split("USER:", 1)
        system_part = parts[0].replace("SYSTEM:", "", 1).strip()
        system_prompt = system_part
        user_prompt = parts[1].strip()
    return system_prompt, user_prompt


def generate_analytical_summary(
    profile_json_str: str,
    timeout: float = 20.0,
) -> str:
    """
    Generate a deep analytical explanation from a serialised profile JSON string.

    Uses the ``analytical_explanation.txt`` prompt template which instructs the
    LLM to reason causally about skill alignment, education relevance, ability
    implications, strength-risk tradeoff, and development trajectory.

    This function is **synchronous** so it can be run via
    ``asyncio.get_event_loop().run_in_executor(None, generate_analytical_summary, ...)``
    from async callers.

    Parameters
    ----------
    profile_json_str:
        JSON-serialised dict containing profile fields (skills, interests,
        education_level, ability_score, goals, top_career, score_breakdown, …).
    timeout:
        Per-request HTTP timeout forwarded to the underlying Ollama client.
        Caller should set this to a budget that fits within the outer pipeline
        timeout (default 20 s).

    Returns
    -------
    str
        Generated analytical text, or ``""`` on any failure (circuit-breaker
        open, timeout, empty response).  The caller is responsible for applying
        its own fallback when an empty string is returned.
    """
    template = _load_analytical_template()
    if not template:
        logger.warning("Analytical explanation template missing — skipping LLM call")
        return ""

    filled = template.replace("{{profile_json}}", profile_json_str)
    system_prompt, user_prompt = _split_system_user(filled)

    client = get_ollama_client()

    # Save and restore client timeout so we don't permanently mutate the singleton
    _orig_timeout = client._timeout
    try:
        client.configure(timeout=max(5.0, timeout * 0.9))
        response = client.generate(
            prompt=user_prompt,
            system_prompt=system_prompt or None,
            temperature=0.4,
            max_tokens=600,
        )
    except Exception as exc:
        logger.warning("generate_analytical_summary: LLM call raised %s: %s", type(exc).__name__, exc)
        return ""
    finally:
        try:
            client.configure(timeout=_orig_timeout)
        except Exception:
            pass

    if response.success and response.text and len(response.text.strip()) >= 10:
        return response.text.strip()

    logger.debug(
        "generate_analytical_summary: non-success response (error=%r, text_len=%d)",
        response.error,
        len(response.text),
    )
    return ""
